#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
"""
Initially Generated By:
    python -m utool --tf setup_repo --repo=mtgmonte --codedir=~/code --modname=mtgmonte
"""
from __future__ import absolute_import, division, print_function, unicode_literals


def mtgmonte_main():
    ignore_prefix = []
    ignore_suffix = []
    import utool as ut
    # allows for --tf
    ut.main_function_tester('mtgmonte', ignore_prefix, ignore_suffix)

if __name__ == '__main__':
    """
    Usage:
        python -m mtgmonte --tf <funcname>
    """
    print('Running mtgmonte main')
    mtgmonte_main()
